### ISSUE TITLE
An IMPORT that resolves to nothing is silent: the module stays green unless it references an imported name

### ISSUE THREAD

**Issue by mengwong** [smucclaw/l4-ide#971]
An `IMPORT` whose target cannot be resolved produces no diagnostic. If the importing module references nothing from it, `l4 check` and `l4 run` are green. If it does reference imported names, the only symptom is `I could not find a definition for the identifier …` once per referenced name, which reads as broken source rather than a failed import. So a mistyped or unresolvable import can leave a module green.

Found through Hebrew-named modules: `IMPORT` of a Hebrew basename (bare or backticked, with or without a hyphen) resolves to nothing, while a Hebrew-named module runs green on its own and imports Latin-named modules fine. A Latin-target control isolates the basename from the hyphen, from `@lang he`, and from the imported module's Hebrew content. Six probes and the exact recipe are in legalese/canon `subjects/il/hvac-work-licensing-2025/encodings/legalese-he/NOTES.md` (section 4), branch `mengwong/drafts`.

Two asks: (1) an unresolvable `IMPORT` should be a diagnostic at the import line; (2) separately, non-ASCII basenames should resolve, or be refused loudly.

Observed 2026-09-21 on the `unstable` build at `7af775364`. Same silent family as the self-import `GraphException` noted in CLAUDE.md section 5.

**Comment by mengwong** [comment]
Resolved by legalese/l4-ide#451 — https://github.com/legalese/l4-ide/pull/451 (merged to unstable at f8e6e4be9).

One correction to the report as filed: the silence was not about Hebrew or non-ASCII paths as such. A plainly misspelled import name was already reported loudly. What went silent was an import whose path round-tripped through URI percent-escaping and came back a different string, so the resolver's candidate table never matched and nothing was logged. The fix makes an unresolved import a diagnostic at the import site regardless of how the path failed, with `not-ok/import/unresolved-*.l4` fixtures and goldens covering both the plain-typo and the escaped-path cases.
